/// SQL keywords recognized by the parser.
///
/// The lexer emits all identifiers as `SyntaxKind::BareWord`. The parser uses
/// `Parser::at_keyword()` with case-insensitive comparison to distinguish
/// keywords from regular identifiers. This enum lists every keyword the
/// parser currently needs to recognize.
#[derive(Debug, Copy, Clone)]
#[allow(dead_code)]
pub enum Keyword {
    // Clauses
    Select,
    From,
    Where,
    Order,
    By,
    Group,
    Having,
    Limit,
    Offset,
    With,
    As,
    On,
    Using,
    Between,
    In,
    Like,
    Ilike,
    Regexp,
    Is,
    Not,
    Case,
    When,
    Then,
    Else,
    End,
    Cast,
    Distinct,
    All,
    Exists,

    // Logical operators
    And,
    Or,

    // Joins
    Join,
    Inner,
    Left,
    Right,
    Full,
    Outer,
    Cross,
    Global,
    Any,
    Semi,
    Anti,
    Asof,
    Natural,
    Array,
    Final,

    // ORDER BY modifiers
    Asc,
    Desc,
    Nulls,
    First,
    Last,

    // GROUP BY modifiers
    Totals,
    Rollup,
    Cube,

    // Set operations
    Union,
    Except,
    Intersect,

    // DML
    Insert,
    Into,
    Values,
    Delete,
    Update,
    Set,

    // DDL
    Create,
    Alter,
    Drop,
    Detach,
    Attach,
    Rename,
    Truncate,
    Show,
    Use,
    Optimize,
    System,
    Exchange,
    Undrop,

    // Table/Entity keywords
    Table,
    View,
    Database,
    Dictionary,
    Function,
    Materialized,
    Temporary,
    If,
    Replace,
    Live,

    // Column keywords
    Default,
    Codec,
    Ttl,
    Comment,
    Primary,
    Key,
    Alias,
    Ephemeral,

    // ClickHouse-specific clauses
    Prewhere,
    Settings,
    Format,
    Sample,

    // Literals
    Null,
    True,
    False,

    // Types / INTERVAL
    Interval,

    // CREATE TABLE specifics
    Engine,
    Partition,
    Cluster,
    To,
    Populate,
    Empty,
    Permanently,
    After,

    // Column/Index definition
    Column,
    Index,
    Projection,
    Constraint,
    Add,
    Modify,
    Clear,
    Move,
    Granularity,
    Type,
    Deduplicate,

    // EXPLAIN / DESCRIBE
    Explain,
    Describe,
    Ast,
    Plan,
    Pipeline,
    Estimate,
    QueryTree,

    // SHOW specifics
    Tables,
    Databases,
    Columns,
    Dictionaries,
    Functions,
    Processlist,
    Privileges,
    Grants,
    // SYSTEM commands
    Reload,
    Flush,
    Stop,
    Start,
    Merges,
    Replica,
    Replicas,
    Distributed,
    Sending,
    Fetches,
    Moves,
    Logs,
    Cache,
    Dns,
    Mark,
    Uncompressed,
    Compiled,
    Models,
    Disks,
    FilesystemCache,

    // Access control
    Grant,
    Revoke,
    User,
    Role,
    Quota,
    Policy,
    Profile,
    Row,
    // KILL
    Kill,
    Query,
    Mutation,
    Sync,
    Async,
    Test,

    // CHECK / EXISTS / ASSUME
    Check,
    Assume,

    // Transaction
    Begin,
    Commit,
    Rollback,
    Transaction,

    // BACKUP / RESTORE
    Backup,
    Restore,

    // SYSTEM subcommand keywords
    Config,
    Sends,
    Replicated,

    // Dictionary clause keywords
    Min,
    Max,

    // Misc
    Local,
    Freeze,
    Unfreeze,
    Fetch,
    Apply,
    Deleted,
    Source,
    Layout,
    Lifetime,
    Range,
    Hashed,
    Flat,
    Complex,
    Direct,
    Injective,
    Hierarchical,

    // Window functions
    Window,
    Over,
    Rows,
    Groups,
    Unbounded,
    Preceding,
    Following,
    Current,

    // Additional operators
    Isnull,
    Div,
    Mod,

    // WITH FILL
    Fill,
    Step,
    Staleness,
    Interpolate,

    // Access control keywords
    Identified,
    Host,
    Keyed,

    // Recursive CTE
    Recursive,

    // JSON type parameters
    Skip,

    // Aggregate function modifiers
    Ignore,
    Respect,

    // TRIM(BOTH|LEADING|TRAILING ... FROM ...)
    Trim,
    Both,
    Leading,
    Trailing,

    // GROUPING SETS
    Grouping,
    Sets,

    // PARTITION ID
    Id,

    // LIMIT modifiers
    Ties,

    // QUALIFY clause
    Qualify,

    // FILTER clause
    Filter,

    // OPTIMIZE modifiers
    Cleanup,

    // Missing keywords for specific parsers
    Syntax,
    Tree,
    Override,
    Engines,
    For,
    Part,
    Materialize,
    Setting,
    Reset,
    Option,
}

impl Keyword {
    pub fn as_str(&self) -> &'static str {
        match self {
            Keyword::Select => "SELECT",
            Keyword::From => "FROM",
            Keyword::Where => "WHERE",
            Keyword::Order => "ORDER",
            Keyword::By => "BY",
            Keyword::Group => "GROUP",
            Keyword::Having => "HAVING",
            Keyword::Limit => "LIMIT",
            Keyword::Offset => "OFFSET",
            Keyword::With => "WITH",
            Keyword::As => "AS",
            Keyword::On => "ON",
            Keyword::Using => "USING",
            Keyword::Between => "BETWEEN",
            Keyword::In => "IN",
            Keyword::Like => "LIKE",
            Keyword::Ilike => "ILIKE",
            Keyword::Regexp => "REGEXP",
            Keyword::Is => "IS",
            Keyword::Not => "NOT",
            Keyword::Case => "CASE",
            Keyword::When => "WHEN",
            Keyword::Then => "THEN",
            Keyword::Else => "ELSE",
            Keyword::End => "END",
            Keyword::Cast => "CAST",
            Keyword::Distinct => "DISTINCT",
            Keyword::All => "ALL",
            Keyword::Exists => "EXISTS",
            Keyword::And => "AND",
            Keyword::Or => "OR",
            Keyword::Join => "JOIN",
            Keyword::Inner => "INNER",
            Keyword::Left => "LEFT",
            Keyword::Right => "RIGHT",
            Keyword::Full => "FULL",
            Keyword::Outer => "OUTER",
            Keyword::Cross => "CROSS",
            Keyword::Global => "GLOBAL",
            Keyword::Any => "ANY",
            Keyword::Semi => "SEMI",
            Keyword::Anti => "ANTI",
            Keyword::Asof => "ASOF",
            Keyword::Natural => "NATURAL",
            Keyword::Array => "ARRAY",
            Keyword::Final => "FINAL",
            Keyword::Asc => "ASC",
            Keyword::Desc => "DESC",
            Keyword::Nulls => "NULLS",
            Keyword::First => "FIRST",
            Keyword::Last => "LAST",
            Keyword::Totals => "TOTALS",
            Keyword::Rollup => "ROLLUP",
            Keyword::Cube => "CUBE",
            Keyword::Union => "UNION",
            Keyword::Except => "EXCEPT",
            Keyword::Intersect => "INTERSECT",
            Keyword::Insert => "INSERT",
            Keyword::Into => "INTO",
            Keyword::Values => "VALUES",
            Keyword::Delete => "DELETE",
            Keyword::Update => "UPDATE",
            Keyword::Set => "SET",
            Keyword::Create => "CREATE",
            Keyword::Alter => "ALTER",
            Keyword::Drop => "DROP",
            Keyword::Detach => "DETACH",
            Keyword::Attach => "ATTACH",
            Keyword::Rename => "RENAME",
            Keyword::Truncate => "TRUNCATE",
            Keyword::Show => "SHOW",
            Keyword::Use => "USE",
            Keyword::Optimize => "OPTIMIZE",
            Keyword::System => "SYSTEM",
            Keyword::Exchange => "EXCHANGE",
            Keyword::Undrop => "UNDROP",
            Keyword::Table => "TABLE",
            Keyword::View => "VIEW",
            Keyword::Database => "DATABASE",
            Keyword::Dictionary => "DICTIONARY",
            Keyword::Function => "FUNCTION",
            Keyword::Materialized => "MATERIALIZED",
            Keyword::Temporary => "TEMPORARY",
            Keyword::If => "IF",
            Keyword::Replace => "REPLACE",
            Keyword::Live => "LIVE",
            Keyword::Default => "DEFAULT",
            Keyword::Codec => "CODEC",
            Keyword::Ttl => "TTL",
            Keyword::Comment => "COMMENT",
            Keyword::Primary => "PRIMARY",
            Keyword::Key => "KEY",
            Keyword::Alias => "ALIAS",
            Keyword::Ephemeral => "EPHEMERAL",
            Keyword::Prewhere => "PREWHERE",
            Keyword::Settings => "SETTINGS",
            Keyword::Format => "FORMAT",
            Keyword::Sample => "SAMPLE",
            Keyword::Null => "NULL",
            Keyword::True => "TRUE",
            Keyword::False => "FALSE",
            Keyword::Interval => "INTERVAL",
            Keyword::Engine => "ENGINE",
            Keyword::Partition => "PARTITION",
            Keyword::Cluster => "CLUSTER",
            Keyword::To => "TO",
            Keyword::Populate => "POPULATE",
            Keyword::Empty => "EMPTY",
            Keyword::Permanently => "PERMANENTLY",
            Keyword::After => "AFTER",
            Keyword::Column => "COLUMN",
            Keyword::Index => "INDEX",
            Keyword::Projection => "PROJECTION",
            Keyword::Constraint => "CONSTRAINT",
            Keyword::Add => "ADD",
            Keyword::Modify => "MODIFY",
            Keyword::Clear => "CLEAR",
            Keyword::Move => "MOVE",
            Keyword::Granularity => "GRANULARITY",
            Keyword::Type => "TYPE",
            Keyword::Deduplicate => "DEDUPLICATE",
            Keyword::Explain => "EXPLAIN",
            Keyword::Describe => "DESCRIBE",
            Keyword::Ast => "AST",
            Keyword::Plan => "PLAN",
            Keyword::Pipeline => "PIPELINE",
            Keyword::Estimate => "ESTIMATE",
            Keyword::QueryTree => "QUERY",
            Keyword::Tables => "TABLES",
            Keyword::Databases => "DATABASES",
            Keyword::Columns => "COLUMNS",
            Keyword::Dictionaries => "DICTIONARIES",
            Keyword::Functions => "FUNCTIONS",
            Keyword::Processlist => "PROCESSLIST",
            Keyword::Privileges => "PRIVILEGES",
            Keyword::Grants => "GRANTS",
            Keyword::Reload => "RELOAD",
            Keyword::Flush => "FLUSH",
            Keyword::Stop => "STOP",
            Keyword::Start => "START",
            Keyword::Merges => "MERGES",
            Keyword::Replica => "REPLICA",
            Keyword::Replicas => "REPLICAS",
            Keyword::Distributed => "DISTRIBUTED",
            Keyword::Sending => "SENDING",
            Keyword::Fetches => "FETCHES",
            Keyword::Moves => "MOVES",
            Keyword::Logs => "LOGS",
            Keyword::Cache => "CACHE",
            Keyword::Dns => "DNS",
            Keyword::Mark => "MARK",
            Keyword::Uncompressed => "UNCOMPRESSED",
            Keyword::Compiled => "COMPILED",
            Keyword::Models => "MODELS",
            Keyword::Disks => "DISKS",
            Keyword::FilesystemCache => "FILESYSTEM",
            Keyword::Grant => "GRANT",
            Keyword::Revoke => "REVOKE",
            Keyword::User => "USER",
            Keyword::Role => "ROLE",
            Keyword::Quota => "QUOTA",
            Keyword::Policy => "POLICY",
            Keyword::Profile => "PROFILE",
            Keyword::Row => "ROW",
            Keyword::Kill => "KILL",
            Keyword::Query => "QUERY",
            Keyword::Mutation => "MUTATION",
            Keyword::Sync => "SYNC",
            Keyword::Async => "ASYNC",
            Keyword::Test => "TEST",
            Keyword::Check => "CHECK",
            Keyword::Assume => "ASSUME",
            Keyword::Begin => "BEGIN",
            Keyword::Commit => "COMMIT",
            Keyword::Rollback => "ROLLBACK",
            Keyword::Transaction => "TRANSACTION",
            Keyword::Backup => "BACKUP",
            Keyword::Restore => "RESTORE",
            Keyword::Config => "CONFIG",
            Keyword::Sends => "SENDS",
            Keyword::Replicated => "REPLICATED",
            Keyword::Min => "MIN",
            Keyword::Max => "MAX",
            Keyword::Local => "LOCAL",
            Keyword::Freeze => "FREEZE",
            Keyword::Unfreeze => "UNFREEZE",
            Keyword::Fetch => "FETCH",
            Keyword::Apply => "APPLY",
            Keyword::Deleted => "DELETED",
            Keyword::Source => "SOURCE",
            Keyword::Layout => "LAYOUT",
            Keyword::Lifetime => "LIFETIME",
            Keyword::Range => "RANGE",
            Keyword::Hashed => "HASHED",
            Keyword::Flat => "FLAT",
            Keyword::Complex => "COMPLEX",
            Keyword::Direct => "DIRECT",
            Keyword::Injective => "INJECTIVE",
            Keyword::Hierarchical => "HIERARCHICAL",
            Keyword::Window => "WINDOW",
            Keyword::Over => "OVER",
            Keyword::Rows => "ROWS",
            Keyword::Groups => "GROUPS",
            Keyword::Unbounded => "UNBOUNDED",
            Keyword::Preceding => "PRECEDING",
            Keyword::Following => "FOLLOWING",
            Keyword::Current => "CURRENT",
            Keyword::Isnull => "ISNULL",
            Keyword::Div => "DIV",
            Keyword::Mod => "MOD",
            Keyword::Fill => "FILL",
            Keyword::Step => "STEP",
            Keyword::Staleness => "STALENESS",
            Keyword::Interpolate => "INTERPOLATE",
            Keyword::Identified => "IDENTIFIED",
            Keyword::Host => "HOST",
            Keyword::Keyed => "KEYED",
            Keyword::Recursive => "RECURSIVE",
            Keyword::Skip => "SKIP",
            Keyword::Trim => "TRIM",
            Keyword::Both => "BOTH",
            Keyword::Leading => "LEADING",
            Keyword::Trailing => "TRAILING",
            Keyword::Ignore => "IGNORE",
            Keyword::Respect => "RESPECT",
            Keyword::Grouping => "GROUPING",
            Keyword::Sets => "SETS",
            Keyword::Id => "ID",
            Keyword::Ties => "TIES",
            Keyword::Qualify => "QUALIFY",
            Keyword::Filter => "FILTER",
            Keyword::Syntax => "SYNTAX",
            Keyword::Tree => "TREE",
            Keyword::Override => "OVERRIDE",
            Keyword::Engines => "ENGINES",
            Keyword::For => "FOR",
            Keyword::Part => "PART",
            Keyword::Materialize => "MATERIALIZE",
            Keyword::Setting => "SETTING",
            Keyword::Reset => "RESET",
            Keyword::Option => "OPTION",
            Keyword::Cleanup => "CLEANUP",
        }
    }
}
